"""
Backup System Models

Python dataclasses for backup job tracking and scheduling.
All implementation is in Python 3.10+

Formal Verification:
The preservation set P ⊆ B generated by the GFS retention policy:
P = { b ∈ B | Δt(b) < 7 } ∪ (⋃_{w=1}^{4} min_{t_b} { b ∈ B_w }) ∪ (⋃_{m=1}^{12} min_{t_b} { b ∈ B_m })

Where:
- Δt(b) is the age of backup in days
- B_w is the subset of backups within the w-th week
- B_m is the subset of backups within the m-th month
- t_b is the creation timestamp
"""

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Optional, List, Dict, Any, Set
from enum import Enum
import uuid
import json


class BackupType(Enum):
    """
    Types of backups supported.
    
    FULL: Complete database copy - all data copied
    INCREMENTAL: Changes since last backup using hard links
    """
    FULL = "full"
    INCREMENTAL = "incremental"


class BackupStatus(Enum):
    """
    Backup job status lifecycle.
    
    PENDING: Job created, waiting to start
    IN_PROGRESS: Backup currently running
    COMPLETED: Backup finished successfully
    FAILED: Backup encountered an error
    VERIFIED: Checksum verification passed
    """
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    VERIFIED = "verified"


class BackupFrequency(Enum):
    """
    Backup schedule frequency options.
    
    HOURLY: Run every hour
    DAILY: Run once per day
    WEEKLY: Run once per week
    MONTHLY: Run once per month
    """
    HOURLY = "hourly"
    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"


@dataclass
class BackupJob:
    """
    Represents a single backup job.
    
    Tracks the complete lifecycle of a backup from creation through
    verification. Stored in SQLite for history and analytics.
    
    Attributes:
        id: Unique identifier (UUID)
        user_id: User who initiated the backup
        backup_type: FULL or INCREMENTAL
        status: Current job status
        file_path: Path to the backup file
        file_size_bytes: Size of backup in bytes
        checksum: SHA-256 hash for verification
        record_count: Number of records backed up
        previous_backup_id: For incremental chains
        started_at: When backup started
        completed_at: When backup finished
        verified_at: When checksum was verified
        expires_at: When backup can be deleted per retention
        error_message: Error details if failed
        metadata: Additional JSON metadata
    
    Example:
        >>> job = BackupJob(user_id="user-123", backup_type=BackupType.FULL)
        >>> job.status
        <BackupStatus.PENDING: 'pending'>
    """
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    user_id: str = ""
    backup_type: BackupType = BackupType.FULL
    status: BackupStatus = BackupStatus.PENDING
    file_path: str = ""
    file_size_bytes: int = 0
    checksum: str = ""
    record_count: int = 0
    previous_backup_id: Optional[str] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    verified_at: Optional[datetime] = None
    expires_at: Optional[datetime] = None
    error_message: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert to dictionary for SQLite storage.
        
        Returns:
            Dictionary with all fields serialized for database storage.
        """
        return {
            'id': self.id,
            'user_id': self.user_id,
            'backup_type': self.backup_type.value,
            'status': self.status.value,
            'file_path': self.file_path,
            'file_size_bytes': self.file_size_bytes,
            'checksum': self.checksum,
            'record_count': self.record_count,
            'previous_backup_id': self.previous_backup_id,
            'started_at': self.started_at.isoformat() if self.started_at else None,
            'completed_at': self.completed_at.isoformat() if self.completed_at else None,
            'verified_at': self.verified_at.isoformat() if self.verified_at else None,
            'expires_at': self.expires_at.isoformat() if self.expires_at else None,
            'error_message': self.error_message,
            'metadata': json.dumps(self.metadata),
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'BackupJob':
        """
        Create instance from SQLite row dictionary.
        
        Args:
            data: Dictionary from database row
            
        Returns:
            BackupJob instance
        """
        return cls(
            id=data.get('id', str(uuid.uuid4())),
            user_id=data.get('user_id', ''),
            backup_type=BackupType(data.get('backup_type', 'full')),
            status=BackupStatus(data.get('status', 'pending')),
            file_path=data.get('file_path', ''),
            file_size_bytes=data.get('file_size_bytes', 0),
            checksum=data.get('checksum', ''),
            record_count=data.get('record_count', 0),
            previous_backup_id=data.get('previous_backup_id'),
            started_at=datetime.fromisoformat(data['started_at']) if data.get('started_at') else None,
            completed_at=datetime.fromisoformat(data['completed_at']) if data.get('completed_at') else None,
            verified_at=datetime.fromisoformat(data['verified_at']) if data.get('verified_at') else None,
            expires_at=datetime.fromisoformat(data['expires_at']) if data.get('expires_at') else None,
            error_message=data.get('error_message'),
            metadata=json.loads(data.get('metadata', '{}')),
        )

    def age_days(self) -> int:
        """Calculate age of backup in days."""
        if self.completed_at:
            return (datetime.now() - self.completed_at).days
        return 0

    def is_expired(self) -> bool:
        """Check if backup has passed its expiration date."""
        if self.expires_at:
            return datetime.now() >= self.expires_at
        return False


@dataclass
class BackupSchedule:
    """
    Automated backup schedule configuration.
    
    Defines when automatic backups should be created.
    Managed by BackupScheduler using APScheduler.
    
    Attributes:
        id: Unique identifier
        user_id: User who owns this schedule
        enabled: Whether schedule is active
        frequency: HOURLY, DAILY, WEEKLY, or MONTHLY
        time_of_day: Time to run (HH:MM format, 24h)
        day_of_week: Day for weekly backups (0=Monday, 6=Sunday)
        day_of_month: Day for monthly backups (1-28)
        backup_type: FULL or INCREMENTAL
        retention_daily: Number of daily backups to keep
        retention_weekly: Number of weekly backups to keep
        retention_monthly: Number of monthly backups to keep
        last_run: When schedule last executed
        next_run: When schedule will execute next
    """
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    user_id: str = ""
    enabled: bool = True
    frequency: BackupFrequency = BackupFrequency.DAILY
    time_of_day: str = "02:00"
    day_of_week: int = 6  # Sunday
    day_of_month: int = 1
    backup_type: BackupType = BackupType.FULL
    retention_daily: int = 7
    retention_weekly: int = 4
    retention_monthly: int = 12
    last_run: Optional[datetime] = None
    next_run: Optional[datetime] = None
    created_at: datetime = field(default_factory=datetime.now)
    updated_at: datetime = field(default_factory=datetime.now)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for SQLite storage."""
        return {
            'id': self.id,
            'user_id': self.user_id,
            'enabled': self.enabled,
            'frequency': self.frequency.value,
            'time_of_day': self.time_of_day,
            'day_of_week': self.day_of_week,
            'day_of_month': self.day_of_month,
            'backup_type': self.backup_type.value,
            'retention_daily': self.retention_daily,
            'retention_weekly': self.retention_weekly,
            'retention_monthly': self.retention_monthly,
            'last_run': self.last_run.isoformat() if self.last_run else None,
            'next_run': self.next_run.isoformat() if self.next_run else None,
            'created_at': self.created_at.isoformat(),
            'updated_at': self.updated_at.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'BackupSchedule':
        """Create instance from SQLite row dictionary."""
        return cls(
            id=data.get('id', str(uuid.uuid4())),
            user_id=data.get('user_id', ''),
            enabled=bool(data.get('enabled', 1)),
            frequency=BackupFrequency(data.get('frequency', 'daily')),
            time_of_day=data.get('time_of_day', '02:00'),
            day_of_week=data.get('day_of_week', 6),
            day_of_month=data.get('day_of_month', 1),
            backup_type=BackupType(data.get('backup_type', 'full')),
            retention_daily=data.get('retention_daily', 7),
            retention_weekly=data.get('retention_weekly', 4),
            retention_monthly=data.get('retention_monthly', 12),
            last_run=datetime.fromisoformat(data['last_run']) if data.get('last_run') else None,
            next_run=datetime.fromisoformat(data['next_run']) if data.get('next_run') else None,
            created_at=datetime.fromisoformat(data['created_at']) if data.get('created_at') else datetime.now(),
            updated_at=datetime.fromisoformat(data['updated_at']) if data.get('updated_at') else datetime.now(),
        )


@dataclass
class BackupManifest:
    """
    Backup manifest for integrity verification.
    
    Stored alongside each backup as a JSON file.
    Contains metadata and file checksums.
    
    The manifest enables:
    1. Integrity verification via SHA-256 checksum
    2. Quick metadata lookup without parsing backup
    3. Chain validation for incremental backups
    
    Attributes:
        backup_id: ID of the backup job
        created_at: When backup was created
        backup_type: FULL or INCREMENTAL
        database_checksum: SHA-256 hash of the database file
        file_size_bytes: Size of backup file
        record_count: Total records in backup
        tables: Dict mapping table names to row counts
        previous_backup_id: For incremental chain validation
        checksum_algorithm: Always "sha256"
        version: Manifest format version
    """
    backup_id: str = ""
    created_at: datetime = field(default_factory=datetime.now)
    backup_type: BackupType = BackupType.FULL
    database_checksum: str = ""
    file_size_bytes: int = 0
    record_count: int = 0
    tables: Dict[str, int] = field(default_factory=dict)
    previous_backup_id: Optional[str] = None
    checksum_algorithm: str = "sha256"
    version: str = "1.0"

    def to_json(self) -> str:
        """
        Serialize to JSON string.
        
        Returns:
            JSON string with all manifest data
        """
        return json.dumps({
            'backup_id': self.backup_id,
            'created_at': self.created_at.isoformat(),
            'backup_type': self.backup_type.value,
            'database_checksum': self.database_checksum,
            'file_size_bytes': self.file_size_bytes,
            'record_count': self.record_count,
            'tables': self.tables,
            'previous_backup_id': self.previous_backup_id,
            'checksum_algorithm': self.checksum_algorithm,
            'version': self.version,
        }, indent=2)

    @classmethod
    def from_json(cls, json_str: str) -> 'BackupManifest':
        """
        Deserialize from JSON string.
        
        Args:
            json_str: JSON string containing manifest data
            
        Returns:
            BackupManifest instance
        """
        data = json.loads(json_str)
        return cls(
            backup_id=data.get('backup_id', ''),
            created_at=datetime.fromisoformat(data['created_at']) if data.get('created_at') else datetime.now(),
            backup_type=BackupType(data.get('backup_type', 'full')),
            database_checksum=data.get('database_checksum', ''),
            file_size_bytes=data.get('file_size_bytes', 0),
            record_count=data.get('record_count', 0),
            tables=data.get('tables', {}),
            previous_backup_id=data.get('previous_backup_id'),
            checksum_algorithm=data.get('checksum_algorithm', 'sha256'),
            version=data.get('version', '1.0'),
        )

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for compatibility."""
        return {
            'backup_id': self.backup_id,
            'created_at': self.created_at.isoformat(),
            'backup_type': self.backup_type.value,
            'database_checksum': self.database_checksum,
            'file_size_bytes': self.file_size_bytes,
            'record_count': self.record_count,
            'tables': self.tables,
            'previous_backup_id': self.previous_backup_id,
            'checksum_algorithm': self.checksum_algorithm,
            'version': self.version,
        }


@dataclass
class RestoreResult:
    """
    Result of a restore operation.
    
    Tracks the outcome of restoring from a backup,
    including verification status and any errors.
    
    Attributes:
        success: Whether restore completed successfully
        backup_id: ID of the backup restored
        records_restored: Number of records restored
        tables_restored: Number of tables restored
        duration_seconds: Time taken to restore
        checksum_verified: Whether checksum was verified
        error_message: Error details if failed
        details: Additional metadata
    """
    success: bool = False
    backup_id: str = ""
    records_restored: int = 0
    tables_restored: int = 0
    duration_seconds: float = 0.0
    checksum_verified: bool = False
    error_message: Optional[str] = None
    details: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            'success': self.success,
            'backup_id': self.backup_id,
            'records_restored': self.records_restored,
            'tables_restored': self.tables_restored,
            'duration_seconds': self.duration_seconds,
            'checksum_verified': self.checksum_verified,
            'error_message': self.error_message,
            'details': self.details,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'RestoreResult':
        """Create instance from dictionary."""
        return cls(
            success=data.get('success', False),
            backup_id=data.get('backup_id', ''),
            records_restored=data.get('records_restored', 0),
            tables_restored=data.get('tables_restored', 0),
            duration_seconds=data.get('duration_seconds', 0.0),
            checksum_verified=data.get('checksum_verified', False),
            error_message=data.get('error_message'),
            details=data.get('details', {}),
        )


@dataclass
class DedupRecord:
    """
    Record for tracking deduplicated files.
    
    Used by the DeduplicationEngine to track which files
    have been hard-linked to avoid redundant storage.
    
    Hard-link deduplication bounds total storage:
    S_T = S_{b_0} + Σ_{i=1}^{|P|-1} Σ_{f ∈ ΔF_i} size(f)
    
    Where ΔF_i represents only changed files.
    
    Attributes:
        file_hash: SHA-256 hash of file content
        original_path: Path to original file (first occurrence)
        original_size: Size of original file
        link_count: Number of hard links to this file
        first_seen: When file was first seen
        last_seen: When file was last referenced
    """
    file_hash: str = ""
    original_path: str = ""
    original_size: int = 0
    link_count: int = 1
    first_seen: datetime = field(default_factory=datetime.now)
    last_seen: datetime = field(default_factory=datetime.now)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for SQLite storage."""
        return {
            'file_hash': self.file_hash,
            'original_path': self.original_path,
            'original_size': self.original_size,
            'link_count': self.link_count,
            'first_seen': self.first_seen.isoformat(),
            'last_seen': self.last_seen.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'DedupRecord':
        """Create instance from SQLite row dictionary."""
        return cls(
            file_hash=data.get('file_hash', ''),
            original_path=data.get('original_path', ''),
            original_size=data.get('original_size', 0),
            link_count=data.get('link_count', 1),
            first_seen=datetime.fromisoformat(data['first_seen']) if data.get('first_seen') else datetime.now(),
            last_seen=datetime.fromisoformat(data['last_seen']) if data.get('last_seen') else datetime.now(),
        )


@dataclass
class BackupStatistics:
    """
    Statistics about backup system state.
    
    Used for UI display and monitoring.
    """
    total_backups: int = 0
    total_size_bytes: int = 0
    oldest_backup: Optional[datetime] = None
    newest_backup: Optional[datetime] = None
    successful_backups: int = 0
    failed_backups: int = 0
    last_backup_status: Optional[BackupStatus] = None
    storage_saved_dedup: int = 0  # Bytes saved via deduplication

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'total_backups': self.total_backups,
            'total_size_bytes': self.total_size_bytes,
            'oldest_backup': self.oldest_backup.isoformat() if self.oldest_backup else None,
            'newest_backup': self.newest_backup.isoformat() if self.newest_backup else None,
            'successful_backups': self.successful_backups,
            'failed_backups': self.failed_backups,
            'last_backup_status': self.last_backup_status.value if self.last_backup_status else None,
            'storage_saved_dedup': self.storage_saved_dedup,
        }

    @property
    def total_size_mb(self) -> float:
        """Total size in megabytes."""
        return self.total_size_bytes / (1024 * 1024)

    @property
    def storage_saved_mb(self) -> float:
        """Storage saved in megabytes."""
        return self.storage_saved_dedup / (1024 * 1024)