"""
Retention Policy Engine

GFS (Grandfather-Father-Son) rotation strategy for backup retention.
Implements the preservation set formula from research.

All implementation is in Python 3.10+

The preservation set P ⊆ B generated by the GFS retention policy:
P = { b ∈ B | Δt(b) < 7 } ∪ (⋃_{w=1}^{4} min_{t_b} { b ∈ B_w }) ∪ (⋃_{m=1}^{12} min_{t_b} { b ∈ B_m })

Where:
- Δt(b) is the age of backup in days
- B_w is the subset of backups within the w-th week
- B_m is the subset of backups within the m-th month
- t_b is the creation timestamp
"""

from datetime import datetime, timedelta
from typing import List, Dict, Any, Set, Tuple
from pathlib import Path
import logging

from brain.backup.models import BackupJob, BackupStatus


logger = logging.getLogger(__name__)


class RetentionPolicy:
    """
    GFS (Grandfather-Father-Son) retention policy.
    
    Implements the standard backup rotation strategy:
    - Daily: Keep last N daily backups (Son)
    - Weekly: Keep one backup per week for N weeks (Father)
    - Monthly: Keep one backup per month for N months (Grandfather)
    
    This ensures:
    - Recent granular recovery (daily)
    - Medium-term recovery (weekly)
    - Long-term archival (monthly)
    
    Example:
        >>> policy = RetentionPolicy(daily=7, weekly=4, monthly=12)
        >>> 
        >>> # Get backups to delete
        >>> to_delete = policy.evaluate(backups)
        >>> 
        >>> # Get retention summary
        >>> summary = policy.get_summary(backups)
        >>> print(summary)
        {'daily': 5, 'weekly': 4, 'monthly': 2, 'to_delete': 3}
    """
    
    def __init__(
        self,
        daily: int = 7,
        weekly: int = 4,
        monthly: int = 12,
        min_keep: int = 1
    ):
        """
        Initialize retention policy.
        
        Args:
            daily: Number of daily backups to keep
            weekly: Number of weekly backups to keep (one per week)
            monthly: Number of monthly backups to keep (one per month)
            min_keep: Minimum backups to always keep regardless of policy
        """
        self.daily = daily
        self.weekly = weekly
        self.monthly = monthly
        self.min_keep = min_keep
    
    def evaluate(self, backups: List[BackupJob]) -> List[BackupJob]:
        """
        Evaluate backups against retention policy.
        
        Returns list of backups that should be deleted.
        
        Args:
            backups: List of completed backup jobs
            
        Returns:
            List of BackupJob to delete
        """
        # Filter to completed backups only
        completed = [b for b in backups if b.status == BackupStatus.COMPLETED]
        
        if len(completed) <= self.min_keep:
            return []
        
        # Sort by completion date (newest first)
        completed.sort(key=lambda b: b.completed_at or datetime.min, reverse=True)
        
        # Calculate preservation set
        preserve = self._calculate_preservation_set(completed)
        
        # Return backups not in preservation set
        to_delete = [b for b in completed if b.id not in preserve]
        
        # Ensure we don't delete below minimum
        if len(completed) - len(to_delete) < self.min_keep:
            to_delete = to_delete[:len(completed) - self.min_keep]
        
        return to_delete
    
    def _calculate_preservation_set(self, backups: List[BackupJob]) -> Set[str]:
        """
        Calculate the preservation set using GFS algorithm.
        
        P = { b ∈ B | Δt(b) < 7 } ∪ (⋃_{w=1}^{4} min_{t_b} { b ∈ B_w }) ∪ (⋃_{m=1}^{12} min_{t_b} { b ∈ B_m })
        """
        preserve: Set[str] = set()
        now = datetime.now()
        
        # Group backups by time periods
        daily_backups: Dict[str, List[BackupJob]] = {}
        weekly_backups: Dict[int, List[BackupJob]] = {}
        monthly_backups: Dict[int, List[BackupJob]] = {}
        
        for backup in backups:
            if not backup.completed_at:
                continue
            
            dt = backup.completed_at
            
            # Daily group: YYYY-MM-DD
            day_key = dt.strftime("%Y-%m-%d")
            if day_key not in daily_backups:
                daily_backups[day_key] = []
            daily_backups[day_key].append(backup)
            
            # Weekly group: ISO week number
            week_num = dt.isocalendar()[1]
            year = dt.year
            week_key = year * 100 + week_num
            if week_key not in weekly_backups:
                weekly_backups[week_key] = []
            weekly_backups[week_key].append(backup)
            
            # Monthly group: YYYY-MM
            month_key = dt.year * 100 + dt.month
            if month_key not in monthly_backups:
                monthly_backups[month_key] = []
            monthly_backups[month_key].append(backup)
        
        # Daily retention: Keep backups from last N days
        for i in range(self.daily):
            day = now - timedelta(days=i)
            day_key = day.strftime("%Y-%m-%d")
            if day_key in daily_backups:
                # Keep the latest backup from this day
                day_backups = sorted(
                    daily_backups[day_key],
                    key=lambda b: b.completed_at or datetime.min,
                    reverse=True
                )
                if day_backups:
                    preserve.add(day_backups[0].id)
        
        # Weekly retention: Keep one backup per week for last N weeks
        sorted_weeks = sorted(weekly_backups.keys(), reverse=True)
        for week_key in sorted_weeks[:self.weekly]:
            # Keep the first (oldest) backup from this week
            week_backups = sorted(
                weekly_backups[week_key],
                key=lambda b: b.completed_at or datetime.min
            )
            if week_backups:
                preserve.add(week_backups[0].id)
        
        # Monthly retention: Keep one backup per month for last N months
        sorted_months = sorted(monthly_backups.keys(), reverse=True)
        for month_key in sorted_months[:self.monthly]:
            # Keep the first (oldest) backup from this month
            month_backups = sorted(
                monthly_backups[month_key],
                key=lambda b: b.completed_at or datetime.min
            )
            if month_backups:
                preserve.add(month_backups[0].id)
        
        return preserve
    
    def get_summary(self, backups: List[BackupJob]) -> Dict[str, Any]:
        """
        Get retention summary for backups.
        
        Args:
            backups: List of backup jobs
            
        Returns:
            Dictionary with retention analysis
        """
        completed = [b for b in backups if b.status == BackupStatus.COMPLETED]
        to_delete = self.evaluate(backups)
        
        # Count by period
        now = datetime.now()
        daily_count = 0
        weekly_count = 0
        monthly_count = 0
        
        for backup in completed:
            if not backup.completed_at:
                continue
            
            age = now - backup.completed_at
            
            if age.days < 7:
                daily_count += 1
            elif age.days < 30:
                weekly_count += 1
            else:
                monthly_count += 1
        
        return {
            'total_backups': len(completed),
            'daily_kept': daily_count,
            'weekly_kept': weekly_count,
            'monthly_kept': monthly_count,
            'to_delete': len(to_delete),
            'retention_policy': {
                'daily': self.daily,
                'weekly': self.weekly,
                'monthly': self.monthly,
            }
        }


class RetentionManager:
    """
    Manages retention policy enforcement.
    
    Coordinates with BackupManager to delete expired backups.
    
    Example:
        >>> manager = RetentionManager(backup_manager)
        >>> 
        >>> # Run retention enforcement
        >>> deleted = manager.enforce_retention(user_id='user-123')
        >>> print(f"Deleted {deleted} old backups")
    """
    
    def __init__(
        self,
        backup_manager,
        policy: RetentionPolicy = None
    ):
        """
        Initialize retention manager.
        
        Args:
            backup_manager: BackupManager instance
            policy: RetentionPolicy to use (default: 7/4/12 GFS)
        """
        self.backup_manager = backup_manager
        self.policy = policy or RetentionPolicy()
    
    def enforce_retention(
        self,
        user_id: str = None,
        dry_run: bool = False
    ) -> List[BackupJob]:
        """
        Enforce retention policy by deleting old backups.
        
        Args:
            user_id: Optional user ID filter
            dry_run: If True, don't actually delete
            
        Returns:
            List of backups that were (or would be) deleted
        """
        # Get all backups
        backups = self.backup_manager.list_backups(
            user_id=user_id,
            limit=1000
        )
        
        # Evaluate retention policy
        to_delete = self.policy.evaluate(backups)
        
        if not dry_run:
            # Delete the backups
            for backup in to_delete:
                self.backup_manager.delete_backup(backup.id)
                logger.info(f"Deleted backup {backup.id} per retention policy")
        
        return to_delete
    
    def preview_retention(
        self,
        user_id: str = None
    ) -> Dict[str, Any]:
        """
        Preview retention without deleting.
        
        Args:
            user_id: Optional user ID filter
            
        Returns:
            Dictionary with preview information
        """
        backups = self.backup_manager.list_backups(
            user_id=user_id,
            limit=1000
        )
        
        to_delete = self.policy.evaluate(backups)
        summary = self.policy.get_summary(backups)
        
        return {
            'summary': summary,
            'to_delete': [
                {
                    'id': b.id,
                    'completed_at': b.completed_at.isoformat() if b.completed_at else None,
                    'file_size_bytes': b.file_size_bytes,
                    'file_path': b.file_path,
                }
                for b in to_delete
            ],
            'dry_run': True,
        }
    
    def set_policy(
        self,
        daily: int = None,
        weekly: int = None,
        monthly: int = None
    ) -> None:
        """
        Update retention policy.
        
        Args:
            daily: New daily retention
            weekly: New weekly retention
            monthly: New monthly retention
        """
        if daily is not None:
            self.policy.daily = daily
        if weekly is not None:
            self.policy.weekly = weekly
        if monthly is not None:
            self.policy.monthly = monthly
        
        logger.info(
            f"Updated retention policy: "
            f"daily={self.policy.daily}, "
            f"weekly={self.policy.weekly}, "
            f"monthly={self.policy.monthly}"
        )


class ArchivePolicy:
    """
    Policy for archiving old data before deletion.
    
    Implements soft-delete and archive workflows:
    1. Mark records as archived (soft delete)
    2. Move to archive storage
    3. Delete after recovery window
    
    Example:
        >>> policy = ArchivePolicy(archive_days=30, delete_days=365)
        >>> policy.archive_old_records(db_connection)
    """
    
    def __init__(
        self,
        archive_days: int = 30,
        delete_days: int = 365,
        archive_dir: str = "archive"
    ):
        """
        Initialize archive policy.
        
        Args:
            archive_days: Days before records are archived
            delete_days: Days before archived records are deleted
            archive_dir: Directory for archived data
        """
        self.archive_days = archive_days
        self.delete_days = delete_days
        self.archive_dir = Path(archive_dir)
    
    def get_archive_candidates(
        self,
        connection,
        table: str,
        date_column: str = "created_at"
    ) -> List[Dict[str, Any]]:
        """
        Get records eligible for archiving.
        
        Args:
            connection: Database connection
            table: Table name
            date_column: Column to check for age
            
        Returns:
            List of records to archive
        """
        cursor = connection.cursor()
        
        cutoff = datetime.now() - timedelta(days=self.archive_days)
        
        cursor.execute(f'''
            SELECT * FROM {table}
            WHERE {date_column} < ?
            AND archived_at IS NULL
        ''', (cutoff.isoformat(),))
        
        columns = [desc[0] for desc in cursor.description]
        return [dict(zip(columns, row)) for row in cursor.fetchall()]
    
    def get_delete_candidates(
        self,
        connection,
        table: str
    ) -> List[Dict[str, Any]]:
        """
        Get archived records eligible for deletion.
        
        Args:
            connection: Database connection
            table: Table name
            
        Returns:
            List of records to delete
        """
        cursor = connection.cursor()
        
        cutoff = datetime.now() - timedelta(days=self.delete_days)
        
        cursor.execute(f'''
            SELECT * FROM {table}
            WHERE archived_at < ?
        ''', (cutoff.isoformat(),))
        
        columns = [desc[0] for desc in cursor.description]
        return [dict(zip(columns, row)) for row in cursor.fetchall()]
    
    def archive_records(
        self,
        connection,
        table: str,
        record_ids: List[str],
        id_column: str = "id"
    ) -> int:
        """
        Mark records as archived (soft delete).
        
        Args:
            connection: Database connection
            table: Table name
            record_ids: IDs of records to archive
            id_column: Name of ID column
            
        Returns:
            Number of records archived
        """
        if not record_ids:
            return 0
        
        cursor = connection.cursor()
        now = datetime.now().isoformat()
        
        placeholders = ','.join('?' * len(record_ids))
        
        cursor.execute(f'''
            UPDATE {table}
            SET archived_at = ?
            WHERE {id_column} IN ({placeholders})
        ''', (now, *record_ids))
        
        connection.commit()
        
        logger.info(f"Archived {cursor.rowcount} records from {table}")
        return cursor.rowcount
    
    def purge_records(
        self,
        connection,
        table: str,
        record_ids: List[str],
        id_column: str = "id"
    ) -> int:
        """
        Permanently delete records.
        
        Args:
            connection: Database connection
            table: Table name
            record_ids: IDs of records to delete
            id_column: Name of ID column
            
        Returns:
            Number of records deleted
        """
        if not record_ids:
            return 0
        
        cursor = connection.cursor()
        
        placeholders = ','.join('?' * len(record_ids))
        
        cursor.execute(f'''
            DELETE FROM {table}
            WHERE {id_column} IN ({placeholders})
        ''', record_ids)
        
        connection.commit()
        
        logger.info(f"Purged {cursor.rowcount} records from {table}")
        return cursor.rowcount


def calculate_storage_savings(
    backups: List[BackupJob],
    dedup_enabled: bool = True
) -> Dict[str, Any]:
    """
    Calculate storage savings from retention and deduplication.
    
    Args:
        backups: List of backup jobs
        dedup_enabled: Whether deduplication is enabled
        
    Returns:
        Dictionary with storage analysis
    """
    if not backups:
        return {
            'total_backups': 0,
            'total_size_bytes': 0,
            'potential_savings_bytes': 0,
        }
    
    total_size = sum(b.file_size_bytes for b in backups)
    completed = [b for b in backups if b.status == BackupStatus.COMPLETED]
    
    # Estimate potential savings from retention
    policy = RetentionPolicy()
    to_delete = policy.evaluate(backups)
    retention_savings = sum(b.file_size_bytes for b in to_delete)
    
    # Estimate deduplication savings (typical 80% for unchanged databases)
    dedup_savings = 0
    if dedup_enabled and len(completed) > 1:
        # Assume 80% deduplication rate for similar backups
        avg_size = total_size / len(completed)
        dedup_savings = int(avg_size * (len(completed) - 1) * 0.8)
    
    return {
        'total_backups': len(backups),
        'completed_backups': len(completed),
        'total_size_bytes': total_size,
        'total_size_mb': total_size / (1024 * 1024),
        'retention_savings_bytes': retention_savings,
        'retention_savings_mb': retention_savings / (1024 * 1024),
        'dedup_savings_bytes': dedup_savings,
        'dedup_savings_mb': dedup_savings / (1024 * 1024),
        'total_potential_savings_bytes': retention_savings + dedup_savings,
        'total_potential_savings_mb': (retention_savings + dedup_savings) / (1024 * 1024),
    }